### ISSUE TITLE
Ignore generated files

### ISSUE THREAD

**Issue by jieyouxu** [henryz00/COVID-19-Data-Visualizer-UK#3]
The `dist/` directory contains generated files which should be ignored, as it is extremely easy to become stale.

For deployment, consider configuring a CI/CD (such as Travis). Might be easier if you write a small build script that:

- Deletes `dist/` if it exists.
- Runs suitable build commands.
- Upload the generated files to the correct remote.

**Comment by henryzt** [comment]
Issues solved by pr #4 , still need to figure out another way to deploy files into gh-pages

**Comment by henryzt** [comment]
Travis CI was successfully integrated, many thanks for the advice!
