### ISSUE TITLE
Ignore package-lock.json and yarn.lock

### ISSUE THREAD

**Issue by jieyouxu** [henryz00/COVID-19-Data-Visualizer-UK#5]
It looks like contributors might be using different tooling (`yarn` vs `npm`) which generate different lockfiles respectively.

Keep only *one* of the lock files and specify which package manager to use, or else you likely will get different build results depending on which package manager you are using.

Since this is a website and not a CLI tool or binary, you do *not* need to include the package lock files anyways.

Consider ignoring both `package-lock.json` and `yarn.lock`.

**Comment by henryzt** [comment]
Issues solved by pr #4
