### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by jieyouxu** [henryz00/COVID-19-Data-Visualizer-UK#6]
On mobile platforms, the webpage can become less responsive (i.e. frame rate can drop below 60 FPS, especially on older/weaker mobile platforms).

I see that in your run-time dependencies you depend on `d3`, `highcharts`, `apexcharts` and `fushioncharts`. These dependencies are not light weight by any means.

Consider incorporating something like `webpack` or `rollup` to do several tasks:

- Dead code elimination (tree-shaking) to reduce built `.js` size.
- Serve the run-time javascript through multiple files to mitigate blocking time on waiting for a large single file (see webpack chunks).
- Minification (reduce whitespaces, reduce build javascript size, reduce network bandwidth usage).
- Consider dynamic imports `import()` as recommeded in webpack so you need not load everything at once (see [Code Splitting | Webpack Guides](https://webpack.js.org/guides/code-splitting/)).

**Comment by henryzt** [comment]
With default vue cli settings I think webpack is incorporated to some degree, and most of the tasks will probably run during build already. I will need to dig deeper on webpack's configs to figure out how to optimize further.

**Comment by k-sai-kiranmayee** [comment]
Hello! I'm not entirely sure, however, we can use the concept of lazy-loading, without actually adding the library of [webpack](https://www.npmjs.com/package/webpack).

For example component: () => import(/* webpackChunkName: "_some name for this chunk_" */ "_path of the file_")

Tried to do this for highcharts but was not sure of all the other places, which use highcharts.

If, still want to go further, found this https://cli.vuejs.org/guide/webpack.html

Please correct me if I'm wrong, and can try to help too :)

Thanks!

**Comment by jieyouxu** [comment]
> Hello! I'm not entirely sure, however, we can use the concept of lazy-loading, without actually adding the library of [webpack](https://www.npmjs.com/package/webpack).
> 
> For example component: () => import(/* webpackChunkName: "_some name for this chunk_" */ "_path of the file_")
> 
> Tried to do this for highcharts but was not sure of all the other places, which use highcharts.
> 
> If, still want to go further, found this https://cli.vuejs.org/guide/webpack.html
> 
> Please correct me if I'm wrong, and can try to help too :)
> 
> Thanks!

I believe that is correct - lazy-loading is enabled by the dynamic `import()`s so we can load certain libraries on demand without loading everything at once on initial page load!

**Comment by k-sai-kiranmayee** [comment]
so @jieyouxu, could you kindly provide what are all the components we can do over here so that it doesn't actually impact the others that are implemented already, will do that one now! ;)

**Comment by jieyouxu** [comment]
> so @jieyouxu, could you kindly provide what are all the components we can do over here so that it doesn't actually impact the others that are implemented already, will do that one now! ;)

So @k-sai-kiranmayee, I believe the path of action to take here is to approach this in several steps.

1. Setup some infrastructure. I think `webpack` is needed here.
2. Configure `webpack`; relevent sections:
    - [Code Splitting](https://webpack.js.org/guides/code-splitting/): de-duping, chunk-splitting, prefetching/preloading.
    - [Caching](https://webpack.js.org/guides/caching/): splitting out our code vs vendor code.
    - [Tree-shaking / Dead code elimination](https://webpack.js.org/guides/tree-shaking/).
    - [Lazy loading](https://webpack.js.org/guides/lazy-loading/).
    - [Optimization](https://webpack.js.org/configuration/optimization/).
3. Refactoring steps to convert static imports, i.e. convert those `import xxx from 'some-lib'` into `const xxx = await import('some-lib');`. Note that this uses the **top-level await** language feature. In V8 (so in recent versions of node.js) this is provided by default, but for browser compatibility `babel` will be needed to desugar this into ES6/ES5 etc.

The rationale here for the various optimization steps:

| Optimization | Rationale |
| -------- | --------- |
| Tree-shaking | Eliminate unused code to reduce file size |
| Minification | Reduce whitespaces, smaller names, smaller file size and faster interpreting |
| Code splitting | De-deduplication, smaller chunks to avoid serving a big javascript file at once |
| Caching | Separate our code vs vendor code (if our code changes, clients only need to re-fetch our code, vendor code less likely to change |
| Lazy loading | Some libraries can be imported slightly later if necessary (goal is to have faster initial page load |
| Other optimizations | See `webpack` docs for more details |

I am not entirely familiar with vue.js, so the steps above are to the best of my knowledge and most definitely contain mistakes! 🍿

**Comment by henryzt** [comment]
> so @jieyouxu, could you kindly provide what are all the components we can do over here so that it doesn't actually impact the others that are implemented already, will do that one now! ;)

Thank you @k-sai-kiranmayee ! Although I'm still quite unsure about how will this work, as I feel all the libraries do need to be loaded at the initial page load 😭, I have found all the imports that may be possible to be improved by switching to dynamic import (`d3`, `highcharts` etc as @jieyouxu mentioned), that you could take a look if you feel it can be improved, you are probably way better than me at this :)

[Main.js (Line5)](https://github.com/henryz00/COVID-19-Timeline-Data-Visualizer/blob/dec122b0f44fe617c21692fe4ec64798f6488e73/src/main.js#L5)

[BarRace.vue (d3 Line57)](https://github.com/henryz00/COVID-19-Timeline-Data-Visualizer/blob/dec122b0f44fe617c21692fe4ec64798f6488e73/src/components/BarRace.vue#L57)

[Chart.vue (Line25)](https://github.com/henryz00/COVID-19-Timeline-Data-Visualizer/blob/dec122b0f44fe617c21692fe4ec64798f6488e73/src/components/Chart.vue#L25)

**Comment by k-sai-kiranmayee** [comment]
> I feel all the libraries do need to be loaded at the initial page load 😭

I do felt the same :(, will see if we can do anything, without breaking any

**Comment by henryzt** [comment]
> > I feel all the libraries do need to be loaded at the initial page load 😭
> 
> I do felt the same :(, will see if we can do anything, without breaking any

No pressure tho! The code might be hard to read lol, already appreciate your help :)

**Comment by k-sai-kiranmayee** [comment]
> No pressure tho! The code might be hard to read lol, already appreciate your help :)

This really made my day!! 💯  Thanks for such a lovely response, however, could you please update on how to start the server locally and all **(** _not able to run the server locally :(_ **)**. And also in my machine, it's showing it couldn't install `vue-fusioncharts`.

**Comment by henryzt** [comment]
I have tried downloading a copy and then `yarn install` and `yarn serve` to start the server, it works fine for me!

**Comment by k-sai-kiranmayee** [comment]
Ahhh!! Really? Apologies! I might be distracting from the original issue here, but I forked this repo and from there I cloned and tried to run **_npm install_** (my node version is 8.9.4 and npm is 5.6.0)

Please stop me, if I'm spoiling this issue!!

Thank you!

**Comment by jieyouxu** [comment]
Could you file a separate issue for your installation failure?

<details>
I've tried to install using `npm` (v5.6.0) and `node` (v8.9.4) and succeeded. Could you post your OS (and OS version) info?

Also, could you please post the failure log showing that you can't install `vue-fusioncharts`, so we have more information to help you possible resolve this issue? Thanks @k-sai-kiranmayee.
</details>

**Comment by henryzt** [comment]
I have now added webpack lazy loading for most of the resource-heavy components to finally reduce the load time, (because now as the data gets increasingly larger and this application, unfortunately, loads all of the history data around the world 🥴),  from around 10s to 3s. Would be great if you guys could confirm this.

**Comment by jieyouxu** [comment]
That makes the fresh initial load time *much* better.

Now, for Yet Another Idea:

- We can try to cache the COVID data in the browser (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching).
    - We can set an expiration time to invalidate the cache when the time reaches the next 00:00 UTC+0.
    - This may require that the data provider API endpoints support `Cache-Control` and the likes.
    - Alternatively, we can try to explicitly use relevant Cache APIs in browsers to do browser-local cache.

Doing so will make subsequent visits faster (especially if the COVID-19 data caches haven't expired yet).

**Comment by henryzt** [comment]
This is resolved with the newest version.
